New Ideas
ritsec/ideas pull request #2
Opened 2022-10-13 21:04 UTC by P0nt14c

Adding 5 ideas.

Please accept

2022-10-14 17:07 UTC, BradHacker requested changes
I like most of the ideas. Can you add these ideas to the existing lists and/or make a new list to categorize your ideas?

2022-10-14 17:07 UTC, BradHacker commented on ideas/cool-project.md
> +Write a cool tool, and give a presentation on it!
I like the shilling for the presentations at RITSEC, but this idea seems too generic to fit into the ideas list.

2022-10-14 17:07 UTC, BradHacker commented on ideas/homelab.md
> +Do you have a homelab? Tell the club all about
I think this project would be more about deploying a homelab than presenting about it. These are project ideas more than presentation ideas.

2024-02-16 17:41 UTC, chase1k commented
Right now, I'm going to merge this. I might manually touch up the less elaborated ideas after. But for now, I am grateful for the contributions.

2024-02-16 17:41 UTC, merged